# Generated by Django 3.2.9 on 2021-12-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN')], default='USD', max_length=3)),
                ('value', models.FloatField(default=1)),
                ('To', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN')], default='USD', max_length=3)),
                ('result', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
