# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(280, 20, 101, 31))
        self.MainLabel.setObjectName("MainLabel")
        self.FCs = QtWidgets.QLineEdit(self.centralwidget)
        self.FCs.setGeometry(QtCore.QRect(130, 230, 371, 31))
        self.FCs.setObjectName("FCs")
        self.EnterButton = QtWidgets.QPushButton(self.centralwidget)
        self.EnterButton.setGeometry(QtCore.QRect(270, 370, 93, 28))
        self.EnterButton.setObjectName("EnterButton")
        self.Edit_line_1_label = QtWidgets.QLabel(self.centralwidget)
        self.Edit_line_1_label.setGeometry(QtCore.QRect(270, 190, 101, 20))
        self.Edit_line_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_line_1_label.setObjectName("Edit_line_1_label")
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(130, 301, 371, 31))
        self.Password.setObjectName("Password")
        self.Edit_line_2_label = QtWidgets.QLabel(self.centralwidget)
        self.Edit_line_2_label.setGeometry(QtCore.QRect(270, 270, 101, 20))
        self.Edit_line_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_line_2_label.setWordWrap(False)
        self.Edit_line_2_label.setObjectName("Edit_line_2_label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(50, 60, 571, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(50, 440, 571, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 70, 20, 381))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(610, 70, 20, 381))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainLabel.setText(_translate("MainWindow", "Exchange Office"))
        self.EnterButton.setText(_translate("MainWindow", "Enter"))
        self.Edit_line_1_label.setText(_translate("MainWindow", "FCs"))
        self.Edit_line_2_label.setText(_translate("MainWindow", "Password"))
